### ISSUE TITLE
Opencdm Update API Timeout/Lockup issues for widevine.

### ISSUE THREAD

**Issue by SR-Lavanyaa** [WebPlatformForEmbedded/Thunder#130]
**branch:** master , WPEFramework 
 
**Reproducible with commit Id** - <62dfa673835c962dbf825eee11dfe9a3429c934f>
using https://github.com/WebPlatformForEmbedded/OCDM-Widevine plugin(ac3a765bdf96027fcb4ff67b0ca69858eb5dd665).
 
In Master Branch the Source File Location:  WPEFramework/Source/ocdm/ExtendedOpenCDMSession.h
In the tested commit SHA - Source File Location:   WPEFramework/Source/ocdm/open_cdm.cpp:
 
**Issue:**
 
In cases where the License Server or application provides an incorrect license response blob to the opencdm update API the caller thread gets blocked infinitely. OpenCdm::Update API goes into a wait state with infinite wait.
__state.WaitState(SESSION_UPDATE | SESSION_MESSAGE, WPEFramework::Core::infinite);_
 
The WaitState() function inside OpenCDM::Update API , Not able to acquire the second Lock() , it seems some other thread has already acquired the lock() and it hangs inside while loop.
 
 
**Note:** 1. Tested this scenario using RELEASE builds.
                2. In Update API the value of [WPEFramework::Core::infinite] is "-1".
                3. With a code walkthough of Wpeframework ,we could see several instances of Wait Timeouts being changed from Infinite to 20 sec (eg) ,
but unfortunately such a switch seems to be missing for the OpenCDM::Update API flows.
 
Since Opencdm::Update API is called from our main media player process thread any erroneous invocation of the API results in lockup of the mediaplayer. 

**CODE SNIPPET:**
 
**WPEFramework/Source/ocdm/open_cdm.cpp:**
 
KeyStatus Update(const uint8_t* pbResponse, const uint16_t cbResponse, std::string& response) {
 
        _state = static_cast<sessionState>(_state & (~(SESSION_UPDATE|SESSION_MESSAGE)));
 
        OpenCDMSession::Update(pbResponse, cbResponse);
 
        _state.WaitState(SESSION_UPDATE | SESSION_MESSAGE, WPEFramework::Core::infinite);
        if ((_state & SESSION_MESSAGE) == SESSION_MESSAGE) {
                response = "message:" + _message;
        }
 
        return CDMState(_key);
}

**Comment by pwielders** [comment]
Must admit, did only see the pull request. and now start reading the issue :-) This is indeed a hidden issue. The Callback will continue if you issue an error if the update can not continue. We had the same issue in PR, where an update did not trigger the callback because there was no key change and the error was not send. We just added the reportin g on an erro. This makes the system also more responsive as now, when you tdetect there is an error during the update, you issue the error, the update that is waiting infinite for a callback sess an error udpate and thus will imidiatly continue without wiating for the 20 Seconds

**Comment by SR-Lavanyaa** [comment]
@pwielders Can you please provide the details of the issue ,which has been fixed in PlayReady plugin for the error scenario of update API callback.

**Comment by SR-Lavanyaa** [comment]
@pwielders - In cases where the License Server or application provides an Incorrect License Response blob to the opencdm update API, 
In OCDM-Widevine Plugin , MediaKeySession::Update() API gets called and in turns it calls MediaKeySession::onKeyStatusChange() function to update the keyStatus.
In that we are getting widevine::Cdm::KeyStatusMap as empty from widevine library. Hence OnKeyStatusUpdate() did not happend and Update API call wait for infinite time.
 
The same code is available in OCDM-Widevine-Nexus-SVP  Plugin.  We don't see any difference over here. The problem may occur in that plugin too.
Kindly, Provide your feedback. 

Please find code snippet below:

**CODE SNIPPET:**
--------------

_void MediaKeySession::Update(
    const uint8_t *f_pbKeyMessageResponse,
    uint32_t f_cbKeyMessageResponse) {
  
  std::string keyResponse(reinterpret_cast<const char*>(f_pbKeyMessageResponse),
      f_cbKeyMessageResponse);
  if (widevine::Cdm::kSuccess != m_cdm->update(m_sessionId, keyResponse))
  {
     **onKeyStatusChange();**
  }
  
}

void MediaKeySession::onKeyStatusChange()
{
     **widevine::Cdm::KeyStatusMap map;**
     if (widevine::Cdm::kSuccess != m_cdm->**getKeyStatuses(m_sessionId, &map)**)
     {
         return;
     }

     for (const auto& pair : map) {
         const std::string& keyValue = pair.first;
         widevine::Cdm::KeyStatus keyStatus = pair.second;
         
         **m_piCallback->OnKeyStatusUpdate(widevineKeyStatusToCString(keyStatus),
                                         reinterpret_cast<const uint8_t*>(keyValue.c_str()),
                                         keyValue.length());**
     }
}_

**Comment by pwielders** [comment]
The issue with PR is a bit easier as it is only expecting 1 key. So on any update, if something fails, the full session is moved into an Error state. By changing to the error state the blocked update is released with an error message. See:https://github.com/WebPlatformForEmbedded/OCDM-Playready/blob/master/MediaSession.cpp#L465. Due to this call, any pending wait will continue.
So looking at your proposal, my suggestion would be that if you get an error situation, the session (owning all keys) should move to an Error state. That means that, taking your snippit:

```
void MediaKeySession::Update(
const uint8_t *f_pbKeyMessageResponse,
uint32_t f_cbKeyMessageResponse) {

std::string keyResponse(reinterpret_cast<const char*>(f_pbKeyMessageResponse),
f_cbKeyMessageResponse);
if (widevine::Cdm::kSuccess != m_cdm->update(m_sessionId, keyResponse))
{
onKeyStatusError();
}
else
{
onKeyStatusChange();
}
```
Than there is always a state change (and thus an update on which the Callback is waiting)

**Comment by SR-Lavanyaa** [comment]
@pwielders Thanks for the update. Will test the scenario with OnKeyStatusError()  change and will provide the feedback on the same.

**Comment by pwielders** [comment]
Great. Thanks, awaiting your feedback!

**Comment by SR-Lavanyaa** [comment]
@pwielders As per your suggestion in case of failure,  modified the code as OnKeyStatusError(status) .
Now the update API doesn't hang and throwing the error properly.

We have few queries and updates related to this change,

1. Need to add SESSION_ERROR in WPEFramework/Source/ocdm/open_cdm.cpp,  in case we are throwing error for an update call in failure case.
**Note:** SESSION_UPDATE and SESSION_MESSAGE only previously present.
---------

**CODE SNIPPET:**
-------------
**WPEFramework/Source/ocdm/open_cdm.cpp:**
------------------------------------------------------

KeyStatus Update(const uint8_t* pbResponse, const uint16_t cbResponse, std::string& response) {
    _state = static_cast<sessionState>(_state & (~(SESSION_UPDATE|SESSION_MESSAGE)));

    OpenCDMSession::Update(pbResponse, cbResponse);

    _state.WaitState(SESSION_UPDATE | SESSION_MESSAGE |  SESSION_ERROR , WPEFramework::Core::infinite);   **----- //Here the SESSION_ERROR added.**
    if ((_state & SESSION_MESSAGE) == SESSION_MESSAGE) {
            response = "message:" + _message;
    }

    return CDMState(_key);
}

2. If the below change is approved, do we need to raise pull request for OCDM-Widevine-Nexus-SVP plugin or metrological team will do?

**CODE SNIPPET:**
---------------------
void MediaKeySession::Update(
const uint8_t *f_pbKeyMessageResponse,
uint32_t f_cbKeyMessageResponse) {

std::string keyResponse(reinterpret_cast<const char*>(f_pbKeyMessageResponse),
f_cbKeyMessageResponse);
widevine::Cdm::Status status = m_cdm->update(m_sessionId, keyResponse);

if (widevine::Cdm::kSuccess != status)
{
onKeyStatusError(status);
}
else
{
onKeyStatusChange();
}

**Comment by pwielders** [comment]
Agree, error handling is not "fully" passed down the line. Looking forward to you pull requests :-)

**Comment by SR-Lavanyaa** [comment]
@pwielders I have raised two pull request for this issue.
Kindly review both of the request.

https://github.com/WebPlatformForEmbedded/OCDM-Widevine-Nexus-SVP/pull/3
and one more is #134. (#134 contains two commits , kindly review the same)

**Comment by pwielders** [comment]
Currently you have the "changes" only on the update, but I think we need to align all the methods to this behaviour, so not only the update. So suggest to update also the other waits in this file to use the a_time

**Comment by SR-Lavanyaa** [comment]
@pwielders There is one more change related to this issue. Kindly review it.

https://github.com/WebPlatformForEmbedded/OCDM-Widevine-Nexus-SVP/pull/3
