### ISSUE TITLE
Build instructions and dependencies documentation request.

### ISSUE THREAD

**Issue by WizzerWorks** [WebPlatformForEmbedded/Thunder#169]
Is there any documentation on how to build Thunder? I think I am running into a gcc version 4.8.4 issue. I don't think gcc supports the 'align' std feature.

What is the compiler version you use for Linux build? I am trying to build for Ubuntu 14.04 LTS.

FYI: make failed with:

Building CXX object Source/core/CMakeFiles/WPEFrameworkCore.dir/CyclicBuffer.cpp.o
In file included from /media/workarea/msm/Projects/Thunder/Thunder/Source/core/DataElementFile.h:7:0,
                 from /media/workarea/msm/Projects/Thunder/Thunder/Source/core/CyclicBuffer.h:8,
                 from /media/workarea/msm/Projects/Thunder/Thunder/Source/core/CyclicBuffer.cpp:1:
/media/workarea/msm/Projects/Thunder/Thunder/Source/core/DataElement.h: In member function ‘void WPEFramework::Core::DataElement::Align()’:
/media/workarea/msm/Projects/Thunder/Thunder/Source/core/DataElement.h:211:21: error: ‘align’ is not a member of ‘std’
                 if (std::align(sizeof(TYPE), sizeof(TYPE), newPointer, size)) {
                     ^
make[2]: *** [Source/core/CMakeFiles/WPEFrameworkCore.dir/CyclicBuffer.cpp.o] Error 1
make[1]: *** [Source/core/CMakeFiles/WPEFrameworkCore.dir/all] Error 2
make: *** [all] Error 2

**Comment by WizzerWorks** [comment]
I updated my version of gcc to 6.50 and got past this issue.

Build instructions would still be great to have.

**Comment by pwielders** [comment]
This package is build as part of the buildroot package you can find here:
https://github.com/WebPlatformForEmbedded/buildroot
from the "make menuconfig", you should be able to select and deselect all the different plugins.
If you select a default config (e.g. raspberrypi* in the config directory) you should get a fully installable image for the RPI.
The compiler should support C++ 11, So I think any compile higher than GCC 5.X should be sufficient. However if you want to include the WebKitBrowser, a GCC version 6.X or higher is required,
