### ISSUE TITLE
Warning in JSONRPC.h

### ISSUE THREAD

**Issue by gladish** [WebPlatformForEmbedded/Thunder#250]
The following is repeated over and over during build. This probably isn't a problem, but might be better to use std::numeric_limits or some other pre-defined constant of compatible size. This also highlights one of the undesirable side-affects of having so much code in header files. The same header is being compiled over-and-over.

[ 79%] Building CXX object Source/interfaces/CMakeFiles/WPEFrameworkMarshallings.dir/ProxyStubs_Performance.cpp.o
In file included from /home/gladish/work/wpe/Thunder/Source/interfaces/../core/core.h:37:0,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/Module.h:8,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/IPerformance.h:3,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/ProxyStubs_Performance.cpp:8:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h: In member function ‘bool WPEFramework::Core::JSONRPC::Handler::EventIterator::Next()’:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h:446:35: warning: promoted ~unsigned is always non-zero [-Wsign-compare]
                     if (_position == ~0) {
                         ~~~~~~~~~~^~~~~
[ 80%] Building CXX object Source/interfaces/CMakeFiles/WPEFrameworkMarshallings.dir/ProxyStubs_PlayGiga.cpp.o
In file included from /home/gladish/work/wpe/Thunder/Source/interfaces/../core/core.h:37:0,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/Module.h:8,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/IPlayGiga.h:4,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/ProxyStubs_PlayGiga.cpp:8:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h: In member function ‘bool WPEFramework::Core::JSONRPC::Handler::EventIterator::Next()’:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h:446:35: warning: promoted ~unsigned is always non-zero [-Wsign-compare]
                     if (_position == ~0) {
                         ~~~~~~~~~~^~~~~
[ 81%] Building CXX object Source/interfaces/CMakeFiles/WPEFrameworkMarshallings.dir/ProxyStubs_Power.cpp.o
In file included from /home/gladish/work/wpe/Thunder/Source/interfaces/../core/core.h:37:0,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/Module.h:8,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/IPower.h:4,
                 from /home/gladish/work/wpe/Thunder/Source/interfaces/ProxyStubs_Power.cpp:9:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h: In member function ‘bool WPEFramework::Core::JSONRPC::Handler::EventIterator::Next()’:
/home/gladish/work/wpe/Thunder/Source/interfaces/../core/JSONRPC.h:446:35: warning: promoted ~unsigned is always non-zero [-Wsign-compare]
                     if (_position == ~0) {
                         ~~~~~~~~~~^~~~~

**Comment by pwielders** [comment]
Fixed: https://github.com/WebPlatformForEmbedded/Thunder/commit/d579c8d9352a89ad87bb36bc8d36b8ee8b8a41aa
