### ISSUE TITLE
JsonGenerator.py StubGenerator.py having version compatibility issues

### ISSUE THREAD

**Issue by balav08** [WebPlatformForEmbedded/Thunder#302]
While compiling with the latest commit for WPEframework, facing issues with the Python version change. As it changes from python2 to python3.we are facing these errors,
[Error_logs.txt](https://github.com/WebPlatformForEmbedded/Thunder/files/4040446/Error_logs.txt)

If we add ,
-DPYTHON_EXECUTABLE=${STAGING_BINDIR_NATIVE}/python3-native/python3  in recipe and if we try to compile with python3 then the error points to the Python files (JsonGenerator.py, StubGenerator.py as these files are in python2)

The above mentioned files needs to be updated to Python3.
@Khan3033  @moorthy-bs

**Comment by pwielders** [comment]
Scripts have been updated to run using python3.
