### ISSUE TITLE
In glibc_2.31 the stime() was removed that causing build failure in WPEFramework.

### ISSUE THREAD

**Issue by balav08** [WebPlatformForEmbedded/Thunder#321]
With latest glibc_2.31 the stime() was removed and this causes the build failure and It throws the error in wpeframework,

git/Source/core/SystemInfo.cpp . 
Error logs: 
| /../../build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/wpeframework/3.0+gitAUTOINC+9629e13e39-r0/git/Source/core/SystemInfo.cpp:327:13: error: 'stime' was not declared in this scope; did you mean 'ctime'?
|   327 |         if (stime(&value) != 0) {
|       |             ^~~~~
|       |             ctime
| ninja: build stopped: subcommand failed.
| WARNING: /../../build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/wpeframework/3.0+gitAUTOINC+9629e13e39-r0/temp/run.do_compile.532:1 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} } cmake --build '/../../build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/wpeframework/3.0+gitAUTOINC+9629e13e39-r0/build' "$@" -- -j 8 -l 12.0'

Till glibc_2.30 the stime() was declared in "time.h" but with the latest glibc_2.31 the stime() was removed.So, we need to find alternate for the stime().

**Comment by moorthy-bs** [comment]
stime() is deprecated in glibc 2.31. alternative is clock_settime()

**Comment by balav08** [comment]
This changes  wpeframework : Replacing stime() with clocksettime() in SystemInfo.cp… #329  
resolves the stime() issue in wpeframework.
