### ISSUE TITLE
StubGenerator throws TypeError for OCDM when runs on python3

### ISSUE THREAD

**Issue by moorthy-bs** [WebPlatformForEmbedded/Thunder#335]
there are some python 2to3 patches available on meta-wpe that change the python scripts compatible to python3. But the wpeframework build breaks with below error when enabled 'opencdm' that involves stub generation for IOCDM.h

`File "build/tmp/work/aarch64-mx8m-yoe-linux/wpeframework/3.0+gitAUTOINC+21eb30e5fe-r0/recipe-sysroot-native/usr/sbin/ProxyStubGenerator/StubGenerator.py", line 148, in GenerateStubs
    if iface.id < MIN_INTERFACE_ID:
TypeError: '<' not supported between instances of 'str' and 'int'`

On stub generation of IOCDM.h, StubGenerator.py checks Ids.h on the same directory but it is available only on 'Source/com/Ids.h'
ref. [https://github.com/WebPlatformForEmbedded/Thunder/blob/master/Tools/ProxyStubGenerator/StubGenerator.py#L137](https://github.com/WebPlatformForEmbedded/Thunder/blob/master/Tools/ProxyStubGenerator/StubGenerator.py#L137)

**Comment by moorthy-bs** [comment]
Found a dev branch `development/kplata/python3` where python scripts updated to version 3 and the code which causing issue has been removed.
Ref. [https://github.com/WebPlatformForEmbedded/Thunder/blob/development/kplata/python3/Tools/ProxyStubGenerator/StubGenerator.py#L177](https://github.com/WebPlatformForEmbedded/Thunder/blob/development/kplata/python3/Tools/ProxyStubGenerator/StubGenerator.py#L177)

**Comment by pwielders** [comment]
Indeed we are moving to Python3 for the generation of the PS. If you talke all masters it should work. Currently the stuff is uder QA if Oke, we will bump it all.
